---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

```


# Spatial Interpolation using Bayesian Maximum Entropy

The **BMEmapping** R package delivers a flexible, robust, and computationally optimized framework for spatial interpolation and uncertainty quantification using the **Bayesian Maximum Entropy (BME)** paradigm. Unlike traditional kriging frameworks that rely strictly on precise physical measurements (**hard data**), **BMEmapping** allows for the systematic integration of bounded uncertainty domains (**soft-interval data**) without resorting to linear or Gaussian assumptions.

The package features two operational geostatistical engines:

* **Classical BME (CBME):** Integrates structural general-knowledge via user-defined theoretical variogram parameters.
* **Quantile-Based BME (QBME):** Bypasses manual variogram fitting by internally constructing an ensemble of localized, quantile-specific variogram structures to capture spatial continuity adaptively across different levels of the data distribution.

## Installation

You can install the development version of **BMEmapping** from [GitHub](https://github.com/) using `devtools`:

```r
# install.packages("devtools")
devtools::install_github("KinsprideDuah/BMEmapping")

```

## Core Functions

### Data Pipeline Configuration

* **`bme_map`**
Constructs a unified data object encapsulating coordinate structures, spatial attributes, hard measurements, and soft-interval constraints to condition the interpolation space.

### Posterior Density Estimation

* **`prob_zk`**
Computes posterior densities using the CBME approach.
* **`q_prob_zk`**
Computes posterior densities using the QBME approach.


### Probabilistic Spatial Prediction & Uncertainty Estimation

* **`bme_predict`**
Computes spatial point estimates (*mean*, *median*, or *mode*) using the CBME approach.
* **`q_bme_predict`**
Computes spatial point estimates (*mean*, *median*, or *mode*) using the QBME approach.
* **`bme_predict_ci`** 
Constructs credible intervals using the CBME approach.
* **`q_bme_predict_ci`**
Constructs credible intervals using the QBME approach.


### Model Validation & S3 Graphics

* **`bme_cv`**
Executes K-fold or exact Leave-One-Out Cross-Validation (LOOCV) at hard data locations using the CBME approach.
* **`q_bme_cv`**
Executes K-fold or exact LOOCV at hard data locations using the QBME approach.
* **`summary()`**
Provides standard geostatistical error metrics for **BMEmapping** objects.
* **`plot()`**
Provides graphical visualzations (spatial, prediction and residual plots) of **BMEmapping** objects.


## Getting Help

If you encounter a bug or have structural feature requests, please file a ticket alongside a minimal reproducible example (reprex) on the [GitHub Issues page](https://github.com/KinsprideDuah/BMEmapping/issues).

## Author

Kinspride Duah

## License

MIT + file LICENSE
